version: "3.3"
services:
  neo4j:
    container_name: neo4j-db
    #    user: "${UID}:${GID}"
    deploy:
      restart_policy:
        condition: on-failure
    image: neo4j:latest
    environment:
      - NEO4J_AUTH=neo4j/changeme
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_dbms_connector_https_enabled=true
      - NEO4J_dbms_ssl_policy_https_enabled=true
      - NEO4J_dbms_ssl_policy_https_base__directory=/certificates/https
    ports:
      - "7474:7474"
      - "7473:7473"
      - "7687:7687"
    volumes:
      - "./neo4j/data:/data"
      - "./neo4j/logs:/logs"
      - "./neo4j/conf:/conf"
      - "./neo4j/certificates:/certificates"

  frontend:
    container_name: xibalba-frontend
    deploy:
      restart_policy:
        condition: on-failure
    image: baakel/xibalba-frontend:latest
    network_mode: host
#    networks:
#      hostnet: {}

#networks:
#  hostnet:
#    external: true
#    name: host
